language: python
python:
#  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - ffmpeg
      - sox
install:
  - pip install -r requirements.txt
  - python setup.py install -f
script:
  - rm -rf output/
  - pytest
  - cd docs; make clean; make html
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: docs
  local_dir: docs
  on:
    branch: documentation/migration
    condition: $(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))') = "3.8"