language: python
python:
#  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
addons:
  apt:
    packages:
      - ffmpeg
install:
  - pip install -r requirements.txt
  - python setup.py install -f
script:
  - pytest
  - python docs/generate_docs.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: docs
  local_dir: docs
  on:
    branch: master
    condition: $(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))') = "3.8"