language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
cache: pip
addons:
  apt:
    packages:
      - ffmpeg
      - sox
install:
  - pip install -U importlib_metadata
  - pip install -r requirements.txt
  - pip install .
script:
  - rm -rf output/
  - pytest
  - cd docs; make clean; make html; touch build/html/.nojekyll
