language: python
dist: jammy
python:
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11"
  - "3.12"
  - "3.13"
cache: pip
addons:
  apt:
    packages:
      - ffmpeg
      - sox
before_install:
  - python -m pip install --upgrade pip
install:
  - pip install -U importlib_metadata
  - pip install -U setuptools
  - pip install -r requirements.txt
  - pip install .
script:
  - rm -rf output/
  - pytest
  - cd docs; make clean; make html; touch build/html/.nojekyll
