language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
cache: pip
addons:
  apt:
    packages:
      - ffmpeg
      - sox
install:
  - pip list | grep setuptools
  - pip install -r requirements.txt
  - python setup.py install -f
script:
  - rm -rf output/
  - pytest
  - cd docs; make clean; make html; touch build/html/.nojekyll
