language: python

matrix:
  include:
    - python: "3.7"
    - python: "3.8"
    - python: "3.9"
    - python: "3.10"
cache: pip
addons:
  apt:
    packages:
      - ffmpeg
      - sox
install:
  - pip install -U importlib_metadata
  - pip install -r requirements.txt
  - pip install .
script:
  - rm -rf output/
  - pytest
  - cd docs; make clean; make html; touch build/html/.nojekyll
