language: python
python:
  - "3.8"
before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
install:
  - conda env create -f env.yml python=$TRAVIS_PYTHON_VERSION
  - conda activate laac_recordings
  - pip install . --upgrade
script:
  - python -m pytest
  - python docs/generate_docs.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: docs
  local_dir: docs
  on:
    branch: master
    condition: $(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))') = "3.8"