language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda env create -f env.yml
  - conda activate laac_recordings
  - conda install python=$TRAVIS_PYTHON_VERSION
  - python setup.py install -f
script:
  - pytest
  - python docs/generate_docs.py
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  target_branch: docs
  local_dir: docs
  on:
    branch: master
    condition: $(python -c 'import sys; print(".".join(map(str, sys.version_info[:2])))') = "3.8"