name: tests
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    name: Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Setup package
        run: |
          pip3 install -r requirements.txt
          python3 setup.py install -f
      - name: Run pytest
        run: |
          pytest
