name: tests
on: [push]
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: [3.7, 3.8, 3.9]
    name: Tests
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - name: Setup repo
        uses: actions/checkout@v2
      - name: Installing required software
        uses: FedericoCarboni/setup-ffmpeg@v1
      - name: sndfile
        if: matrix.os == 'ubuntu-latest'
        run: | 
          sudo apt-get install libsndfile1-dev
      - name: Setup package
        run: |
          pip3 install -r requirements.txt
          pip3 install . --upgrade
          python3 -m pip install --user pytest
      - name: Run pytest
        run: |
          mkdir output
          python3 -m pytest
