name: tests
on: [push]
jobs:
  build-linux:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        python-version: [ '3.8', '3.9', '3.10', '3.11']
        include:
          - os: 'ubuntu-22.04'
            python-version: '3.7.16'
    name: Tests-linux
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: "actions/setup-python@v3"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: ffmpeg
        id: try1
        continue-on-error: true
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: ffmpeg (retry 1)
        if: ${{ steps.try1.outcome == 'failure' }}
        id: try2
        continue-on-error: true
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: ffmpeg (retry 2)
        if: ${{ steps.try2.outcome == 'failure' }}
        id: try3
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: sndfile
        if: matrix.os == 'ubuntu-latest'
        run: | 
          sudo apt-get install libsndfile1-dev sox
      - name: Setup package
        run: |
          pip install --upgrade setuptools
          pip install -r requirements.txt
          pip install . --upgrade
          python -m pip install --user pytest
      - name: Run pytest
        run: |
          mkdir output
          python -m pytest
# we limit macos testing to x64 as arm64 has some trouble with installing some python versions and ffmpeg
# TODO switch testing to macos arm64 (Apple silicon) at some point
  build-macos:
    strategy:
      matrix:
        os: [macos-13]
        python-version: ['3.7.16', '3.8', '3.9', '3.10', '3.11', '3.12']
    name: Tests-macos
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: "actions/setup-python@v3"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: ffmpeg
        id: try1
        continue-on-error: true
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: ffmpeg (retry 1)
        if: ${{ steps.try1.outcome == 'failure' }}
        id: try2
        continue-on-error: true
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: ffmpeg (retry 2)
        if: ${{ steps.try2.outcome == 'failure' }}
        id: try3
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: Setup package
        run: |
          pip install --upgrade setuptools
          pip install -r requirements.txt
          pip install . --upgrade
          python -m pip install --user pytest
      - name: Run pytest
        run: |
          mkdir output
          python -m pytest
  build-windows:
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    name: Tests-windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: "actions/setup-python@v3"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: ffmpeg
        id: try1
        continue-on-error: true
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: ffmpeg (retry 1)
        if: ${{ steps.try1.outcome == 'failure' }}
        id: try2
        continue-on-error: true
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: ffmpeg (retry 2)
        if: ${{ steps.try2.outcome == 'failure' }}
        id: try3
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          ffmpeg-version: release
          architecture: ''
          github-token: ${{ secrets.GITHUB }}
      - name: Setup package
        run: |
          pip install --upgrade setuptools
          pip install -r requirements.txt
          pip install . --upgrade
          python -m pip install --user pytest
      - name: Run pytest
        run: |
          mkdir output
          python -m pytest
