name: tests
on: [push]
jobs:
  build-linux-macos:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: ['3.7.16', '3.8', '3.9', '3.10', '3.11']
    name: Tests-linux-macos
    runs-on: ${{ matrix.os }}
    # defaults:
    #   run:
    #     shell: bash -l {0}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: "actions/setup-python@v3"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v3
        with:
          token: ${{ secrets.GITHUB }}
      - name: sndfile
        if: matrix.os == 'ubuntu-latest'
        run: | 
          sudo apt-get install libsndfile1-dev sox
      - name: Setup package
        run: |
          pip install -r requirements.txt
          pip install . --upgrade
          python -m pip install --user pytest
      - name: Run pytest
        run: |
          mkdir output
          python -m pytest
  build-windows:
    strategy:
      matrix:
        os: [windows-latest]
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']
    name: Tests-windows
    runs-on: ${{ matrix.os }}
    # defaults:
    #   run:
    #     shell: bash -l {0}
    steps:
      - name: Setup repo
        uses: actions/checkout@v3
      - name: Setup python
        uses: "actions/setup-python@v3"
        with:
          python-version: "${{ matrix.python-version }}"
      - name: ffmpeg
        uses: FedericoCarboni/setup-ffmpeg@v2
        with:
          token: ${{ secrets.GITHUB }}
      - name: sndfile
        if: matrix.os == 'ubuntu-latest'
        run: | 
          sudo apt-get install libsndfile1-dev sox
      - name: Setup package
        run: |
          pip install -r requirements.txt
          pip install . --upgrade
          python -m pip install --user pytest
      - name: Run pytest
        run: |
          mkdir output
          python -m pytest
